[package]
name = "sanngaa"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
html5ever-atoms = "*"
tendril = "*"
xml5ever = "*"
kuchiki = { git = "https://github.com/SimonSapin/kuchiki.git" }
